service: hills-api

provider:
  name: aws
  runtime: nodejs10.x
  reservedConcurrency: 1  # default is account concurrency limit, which is 1000 by default
  timeout: 6  # seconds, default is 6

plugins:
  - serverless-offline

functions:
  graphql:
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
    - http:
        path: graphql
        method: get
