service: hills-api

provider:
  name: aws
  runtime: nodejs10.x
  reservedConcurrency: 1 # default is account concurrency limit, which is 1000 by default
  timeout: 6 # seconds, default is 6

plugins:
  - serverless-offline

package:
  exclude:
    - ./**
    - '!./node_modules/**' # don't re-include this; it'd override excludeDevDependencies
  include:
    - data/countries.csv
    - data/DoBIH_v16_2.csv # TODO remove this once data comes from DynamoDB
    - src/**

functions:
  graphql:
    handler: src/graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get
