service: hills-api

provider:
  name: aws
  region: ${opt:region, env:npm_config_AWS_REGION}
  runtime: nodejs10.x
  reservedConcurrency: 1 # default is account concurrency limit, which is 1000 by default
  stage: ${opt:stage, 'dev'}
  timeout: 6 # seconds, default is 6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource:
        - 'Fn::GetAtt': [HillsTable, Arn]

plugins:
  - serverless-offline

package:
  exclude:
    - ./**
    - '!./node_modules/**' # don't re-include this; it'd override excludeDevDependencies
  include:
    - src/**

functions:
  graphql:
    handler: src/graphql.fn
    environment:
      HILLS_TABLE_NAME: ${self:custom.hillsTableName}
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get

resources:
  Resources:
    HillsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain # retain it & data when undeploying the stack
      Properties:
        TableName: ${self:custom.hillsTableName}
        AttributeDefinitions:
          - AttributeName: number
            AttributeType: N
        KeySchema:
          - AttributeName: number
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

custom:
  hillsTableName: ${self:provider.stage}_HILLS
