service: hills-api

provider:
  name: aws
  region: ${opt:region, '${file(./serverless-shared.yml):constants.defaultRegion}'}
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  timeout: 6 # seconds, sls default is 6, aws default is 3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource:
        # Cross-stack reference - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html
        - Fn::ImportValue: ${self:provider.stage}-HillsTableArn

plugins:
  - serverless-offline
  - serverless-plugin-git-variables
  - serverless-prune-plugin

package:
  exclude:
    - ./**
    - '!./node_modules/**' # don't re-include this; it'd override excludeDevDependencies
  include:
    - src/**

#
# API Gateway proxy integration, which is the simplest method and Serverless' default.
#
# There are arguments for and against, but for a lambda that's only ever called via
# API Gateway it seems to be an ok choice.
#
# For:     https://www.stackery.io/blog/why-you-should-use-api-gateway-proxy-integration-with-lambda
# Against: https://read.acloud.guru/how-you-should-and-should-not-use-the-api-gateway-proxy-integration-f9e35479b993
#
functions:
  graphql:
    handler: src/graphql.fn
    description: ${self:custom.versionInfo}
    # reservedConcurrency cannot be specified on the provider - https://github.com/serverless/serverless/issues/5472
    reservedConcurrency: 1 # low value until API Gateway throttling configured
    environment:
      HILLS_TABLE_NAME: ${file(./serverless-db.yml):custom.hillsTableName}
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: graphql
          method: get
  playground:
    handler: src/playground.fn
    description: ${self:custom.versionInfo}
    reservedConcurrency: 1 # low value until API Gateway throttling configured
    events:
      - http:
          path: playground
          method: get

custom:
  exportGitVariables: false
  prune:
    automatic: true
    number: 3
  versionInfo: ${git:branch}:${git:describeLight} isDirty=${git:isDirty} "${git:message}"
