module.exports = Object.freeze({
  BIRKETT: 'BIRKETT',
  CORBETT: 'CORBETT',
  DONALD: 'DONALD',
  GRAHAM: 'GRAHAM',
  HEWITT: 'HEWITT',
  MARILYN: 'MARILYN',
  MUNRO: 'MUNRO',
  NUTTALL: 'NUTTALL',
  WAINWRIGHT: 'WAINWRIGHT',
});
