#
# Separate stack for the database, to allow separate deployment.
#
# It doesn't need to be deployed nearly as often as the lambdas, which was a problem when
# they were the same serverless.yml (and hence CloudFormation stack).
#
service: hills-api-db

provider:
  name: aws
  # File reference path is relative to working director, not this file
  region: ${opt:region, '${file(./serverless-shared.yml):constants.defaultRegion}'}
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    HillsApiDatabase:
      Type: AWS::RDS::DBCluster
      Properties:
        DBClusterIdentifier: hills-api-db-${self:provider.stage}
        # Create an initial database in this cluster
        DatabaseName: HILLS
        Engine: aurora
        EngineMode: serverless
        ScalingConfiguration:
          AutoPause: true
          MaxCapacity: 1
          MinCapacity: 1
          SecondsUntilAutoPause: 300
        DeletionProtection: true
        MasterUsername: admin
        MasterUserPassword: password
