CREATE TABLE HILLS (
  countries SET('GB-ENG', 'GB-SCT', 'GB-WAL', 'IE', 'IM') NOT NULL,
  geodeticLatitude DECIMAL(8, 6) UNSIGNED NOT NULL, -- 99.999999
  geodeticLongitude DECIMAL(8, 6) SIGNED NOT NULL, -- 99.999999
  gridRef6Easting SMALLINT UNSIGNED NOT NULL,
  gridRef6Northing SMALLINT UNSIGNED NOT NULL,
  gridRefSquare VARCHAR(2) NOT NULL,
  heightFeet DECIMAL(6, 2) UNSIGNED NOT NULL, -- 9999.99
  heightMetres DECIMAL(6, 2) UNSIGNED NOT NULL, -- 9999.99
  lists SET('BIRKETT', 'CORBETT', 'DONALD', 'GRAHAM', 'HEWITT', 'MARILYN', 'MUNRO', 'NUTTALL', 'WAINWRIGHT') NOT NULL,
  number SMALLINT UNSIGNED NOT NULL,
  parentMarilynNumber SMALLINT UNSIGNED NULL,
  rhbSection CHAR(3) NOT NULL,
  PRIMARY KEY (number)
)
