CREATE TABLE HILLS (
  heightFeet DECIMAL(6, 2) NOT NULL, -- 9999.99
  heightMetres DECIMAL(6, 2) NOT NULL, -- 9999.99
  name VARCHAR(100) NOT NULL,
  number MEDIUMINT NOT NULL,
  PRIMARY KEY (number)
)
